In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
url = 'https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'
df = pd.read_csv(url)
df_copy=df.copy()

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
#convert categorical features

In [5]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')

In [10]:
df.dtypes

model_year               int64
origin                  object
fuel_type               object
drivetrain              object
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [9]:
df.dtypes[df.dtypes == 'object']

origin        object
fuel_type     object
drivetrain    object
dtype: object

In [14]:
categorical = df.dtypes[df.dtypes == 'object'].index
categorical

Index(['origin', 'fuel_type', 'drivetrain'], dtype='object')

In [15]:
numerical = df.dtypes[df.dtypes != 'object'].index
numerical

Index(['model_year', 'num_doors', 'engine_displacement', 'num_cylinders',
       'horsepower', 'vehicle_weight', 'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')

In [20]:
#convert all categorical values to lower case and remove spaces
for c in categorical:
    df[c]=df[c].str.lower().str.replace(' ','_')

In [21]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,europe,gasoline,front-wheel_drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,europe,diesel,front-wheel_drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,asia,gasoline,front-wheel_drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,europe,gasoline,front-wheel_drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,usa,diesel,front-wheel_drive,3,2580,7,304.0,4510,17.5,31.0

In [59]:
categorical = df['num_doors', 'num']

Index(['origin', 'fuel_type', 'drivetrain'], dtype='object')

In [22]:
#check null values in numerical
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [23]:
#replace null with zeros
df = df.fillna(0)

In [24]:
df.isnull().sum()

model_year             0
origin                 0
fuel_type              0
drivetrain             0
num_doors              0
engine_displacement    0
num_cylinders          0
horsepower             0
vehicle_weight         0
acceleration           0
fuel_efficiency_mpg    0
dtype: int64

In [28]:
df_clean = df.copy()

### split dataset

In [29]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

In [30]:
df_train = df_train.reset_index(drop=True)
df_full_train = df_full_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [33]:
y_train = df_train.fuel_efficiency_mpg.values
y_full_train = df_full_train.fuel_efficiency_mpg.values
y_test = df_test.fuel_efficiency_mpg.values
y_val = df_val.fuel_efficiency_mpg.values

In [34]:
del df_train['fuel_efficiency_mpg']
del df_full_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

In [35]:
df_train.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration
0,2011,usa,gasoline,front-wheel_drive,4,2370,6,284.0,4280,19.0
1,2012,usa,diesel,all-wheel_drive,3,2460,6,288.0,4580,18.8
2,1985,europe,gasoline,all-wheel_drive,3,2070,6,230.0,4150,20.6
3,2005,europe,diesel,front-wheel_drive,5,2050,5,249.0,4120,0.0
4,2004,asia,gasoline,front-wheel_drive,2,2160,6,241.0,4020,17.9

## Question 1

Let's train a decision tree regressor to predict the fuel_efficiency_mpg variable.

Train a model with max_depth=1.
Which original feature is used for splitting the data? If you use DictVectorizer, map a one-hot feature such as origin=USA back to its original column name.

'vehicle_weight'
'model_year'
'origin'
'fuel_type'

In [72]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_extraction import DictVectorizer

from sklearn.metrics import mean_squared_error

In [42]:
train_dicts = df_train.to_dict(orient='records')

In [43]:
dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dicts)

In [44]:
dv.get_feature_names()

['acceleration',
 'drivetrain=all-wheel_drive',
 'drivetrain=front-wheel_drive',
 'drivetrain=rear-wheel_drive',
 'engine_displacement',
 'fuel_type=diesel',
 'fuel_type=gasoline',
 'fuel_type=hybrid',
 'horsepower',
 'model_year',
 'num_cylinders',
 'num_doors',
 'origin=asia',
 'origin=europe',
 'origin=usa',
 'vehicle_weight']

In [61]:
dt = DecisionTreeRegressor(max_depth=1)

dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [62]:
# Replace feature name with exact name
from sklearn.tree import export_text
print(export_text(dt, feature_names=dv.get_feature_names()))

|--- model_year <= 1997.50
|   |--- value: [28.61]
|--- model_year >  1997.50
|   |--- value: [31.17]

### Ans:1 model_year is used for splitting data

## Question:2

Train a random forest regressor with these parameters:

n_estimators=10
random_state=1
n_jobs=-1 (optional - to make training faster)
What's the RMSE of this model on the validation data?

0.1837
1.837
18.37
183.7

In [78]:
train_dicts = df_train.to_dict(orient='records')
dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dicts)

In [79]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=10, random_state=1, n_jobs=-1)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [82]:
val_dicts = df_val.to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [84]:
y_pred = rf.predict(X_val)

In [85]:
rmse = mean_squared_error(y_val, y_pred, squared=False)
rmse

1.8392210851335953

### Ans:2 RMSE=1.839

## Question 3

Now let's experiment with the n_estimators parameter

Try these values of this parameter: [10, 50, 100, 150].
Set random_state to 1.
Evaluate the model on the validation dataset.
Which value gives the lowest validation RMSE? Consider 3 decimal places for calculating the answer.

10
50
100
150

In [94]:
# now check RF for different n_estimators
scores = []

for n in [10, 50, 100, 150]:
    rf = RandomForestRegressor(n_estimators=n, random_state=1)
    rf.fit(X_train, y_train)
    
    y_pred = rf.predict(X_val)
    rmse = mean_squared_error(y_val, y_pred, squared=False)
    
    scores.append((n, rmse.round(4)))

In [95]:
cols=['no_estimators', 'rmse']
df_scores= pd.DataFrame(scores, columns=cols)
df_scores

   no_estimators    rmse
0             10  1.8392
1             50  1.7729
2            100  1.7682
3            150  1.7677

### Ans:3 n_estimators=150 has mini rmse as 1.767

## Question 4

Let's select the best max_depth:

Try different values of max_depth: [10, 15, 20, 25]
For each of these values,
try different values of n_estimators from [10, 50, 100, 150]
calculate the mean RMSE
Fix the random seed: random_state=1
What's the best max_depth, using the mean RMSE?

10
15
20
25

In [100]:
scores = []

for d in [10,15,20,25]:
    for n in [10, 50, 100, 150]:
            rf = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=1)
            rf.fit(X_train, y_train)

            y_pred = rf.predict(X_val)
            rmse = mean_squared_error(y_val, y_pred, squared=False)
            scores.append((d,n,rmse))

In [101]:
cols=['max_depth', 'no_estimators', 'rmse']
df_scores= pd.DataFrame(scores, columns=cols)
df_scores

    max_depth  no_estimators      rmse
0          10             10  1.786430
1          10             50  1.748302
2          10            100  1.745137
3          10            150  1.744008
4          15             10  1.836676
5          15             50  1.772385
6          15            100  1.769205
7          15            150  1.767774
8          20             10  1.841211
9          20             50  1.772556
10         20            100  1.768005
11         20            150  1.767196
12         25             10  1.839476
13         25             50  1.774411
14         25            100  1.769488
15         25            150  1.768853

In [104]:
df_scores.groupby(['max_depth']).mean('rmse')

           no_estimators      rmse
max_depth
10                  77.5  1.755969
15                  77.5  1.786510
20                  77.5  1.787242
25                  77.5  1.788057

### Ans 4: max_depth = 10 has least mean rmse=1.756

## Question 5

We can extract feature importance information from tree-based models.

At each step of the decision tree learning algorithm, it finds the best split. When doing it, we can calculate "gain" - the reduction in impurity before and after the split. This gain is quite useful in understanding what are the important features for tree-based models.

In Scikit-Learn, tree-based models contain this information in the feature_importances_ field.

For this homework question, we'll find the most important feature:

Train the model with these parameters:
n_estimators=10,
max_depth=20,
random_state=1,
n_jobs=-1 (optional)
Get the feature importance information from this model
What's the most important feature (among these 4)?

vehicle_weight
horsepower
acceleration
engine_displacement

In [109]:
#### Use steps from Q3 to train a random forest model

In [110]:
train_dicts = df_train.to_dict(orient='records')
dv = DictVectorizer(sparse=False)

X_train = dv.fit_transform(train_dicts)

In [111]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=10, max_depth=20, random_state=1, n_jobs=-1)
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, n_estimators=10, n_jobs=-1, random_state=1)

In [112]:
importances = rf.feature_importances_
feature_importance_df = pd.DataFrame({
    'Feature': dv.get_feature_names(),
    'Importance': importances
})

In [118]:
feature_importance_df.sort_values(by='Importance', ascending=False)

                         Feature  Importance
9                     model_year    0.295917
15                vehicle_weight    0.203420
6             fuel_type=gasoline    0.160713
8                     horsepower    0.077732
4            engine_displacement    0.061682
0                   acceleration    0.055387
14                    origin=usa    0.042299
2   drivetrain=front-wheel_drive    0.020116
5               fuel_type=diesel    0.020037
11                     num_doors    0.019322
7               fuel_type=hybrid    0.012821
1     drivetrain=all-wheel_drive    0.007805
10                 num_cylinders    0.007329
12                   origin=asia    0.006652
3    drivetrain=rear-wheel_drive    0.005527
13                 origin=europe    0.003241

In [131]:
slected_features = feature_importance_df[feature_importance_df['Feature'].isin(['vehicle_weight','horsepower','acceleration','engine_displacement'])]
slected_features

                Feature  Importance
0          acceleration    0.055387
4   engine_displacement    0.061682
8            horsepower    0.077732
15       vehicle_weight    0.203420

In [135]:
slected_features.sort_values(by='Importance', ascending=False)

                Feature  Importance
15       vehicle_weight    0.203420
8            horsepower    0.077732
4   engine_displacement    0.061682
0          acceleration    0.055387

### Ans:5 feature vehicle_weight has max importance